### ISSUE TITLE
Convert to cmake

### ISSUE THREAD

**Issue by wythe** [intrig/xenon#45]
- [x] Convert meson build system to use cmake instead (#53)
- [x] Add version number to cmake build (#51)
- [x] Require flex/bison and build asn.1 programs on linux only (see tools/CMakeLists) (#51)
- [x] Verify build and test works on Visual Studio (#51)
- [x] Add Install ability to build (#53)
- [x] Make Travis use cmake instead of meson (#53)
- [x] Remove meson files (#68)
- [x] Install (#64)
