### ISSUE TITLE
Use github actions for CI

### ISSUE THREAD

**Issue by wythe** [intrig/xenon#46]
This is dependent on #45.

- [x] Confirm Github actions can automatically create merge builds on pull requests.
- [x] Convert current Travis based system to use github actions. (#63)
- [x] Add Windows to CI test matrix. (#63)
- [x] Add Install and Install check to CI (#64)
- [x] Remove travis (#68)
